### ISSUE TITLE
Linux build issues

### ISSUE THREAD

**Issue by whoabuddy** [hashhavoc/teller#5]
Something small but documenting for others, initially was unable to build the executable on Linux after a fresh clone:

```
$ go version
go version go1.22.1 linux/amd64
$ go build -o teller
no Go files in /home/whoabuddy/Dev/hashhavoc/teller
$ ls
cmd  config  Dockerfile  go.mod  go.sum  internal  LICENSE  pkg  README.md
```

One suggestion on the internet was to run `go build ./...` but then I get an error about the clipboard:

```
$ go build ./...
# golang.design/x/clipboard
clipboard_linux.c:15:10: fatal error: X11/Xlib.h: No such file or directory
   15 | #include <X11/Xlib.h>
      |          ^~~~~~~~~~~~
compilation terminated.
```

The answer in my case was to install the dependency `libx11-dev` first, then run the build from a subfolder:

```
sudo apt-get install libx11-dev
cd hashhavoc/teller/cmd/teller
go build -o teller
```

**Comment by hashhavoccat** [comment]
Thanks for reporting! Yeah the clipboard is kinda of a headache. It also has issues on windows still looking into how to make that better supported. I have updated the readme here  to include your information https://github.com/hashhavoc/teller/pull/8
